export const NavLinkAPI = [
  { link: "Model S" },
  { link: "Model 3" },
  { link: "Model X" },
  { link: "Model Y" },
  { link: "Solar Roof" },
  { link: "Solar Panels" },
  { link: "Exiting Inventory" },
  { link: "Use Inventory" },
  { link: "Trade In" },
  { link: "Test Drive" },
  { link: "Powerwall" },
  { link: "Commercial Emergy" },
  { link: "Utilities" },
  { link: "Charging" },
  { link: "Finds Us" },
  { link: "Support" },
  { link: "Careers" },
  { link: "Shop" },
  { link: "Account" },
  { link: "More" },
];
